DROP INDEX IF EXISTS idx_als_user_id;
DROP INDEX IF EXISTS idx_als_user_generated;
DROP INDEX IF EXISTS idx_als_latest;
DROP TABLE IF EXISTS output.als_recommendations CASCADE;

CREATE TABLE output.als_recommendations (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES core.user_profiles(id),

    -- Recommendation data (parallel arrays)
    recommended_video_ids INTEGER[] NOT NULL,  -- [101, 202, 303, ...]
    scores DECIMAL(6,4)[] NOT NULL,            -- [0.9823, 0.8512, 0.7763, ...]

    -- Model metadata
    model_version VARCHAR(50) NOT NULL,        -- 'als_v2.1_20251202'
    model_params TEXT,                          -- {"rank": 10, "maxIter": 10, "regParam": 0.1} JSON string

    -- Generation metadata
    candidates_evaluated INTEGER DEFAULT 0,     -- How many videos were considered
    generation_time_ms INTEGER DEFAULT 0,       -- How long it took to generate

    generated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP,                       -- When to regenerate (optional)

    is_active BOOLEAN DEFAULT true              -- Soft delete for versioning
);

-- Get latest recommendations for a user
CREATE INDEX idx_als_user_latest ON output.als_recommendations(user_id, generated_at DESC)
    WHERE is_active = true;

-- Get all recommendations generated by a specific model version
CREATE INDEX idx_als_model_version ON output.als_recommendations(model_version, generated_at DESC);

-- Cleanup old recommendations
CREATE INDEX idx_als_cleanup ON output.als_recommendations(is_active, generated_at) WHERE is_active = false;

CREATE INDEX idx_als_video_recommendations ON output.als_recommendations USING GIN(recommended_video_ids);

-- Function to get latest recommendations for a user
CREATE OR REPLACE FUNCTION get_user_recommendations(p_user_id INTEGER, p_limit INTEGER DEFAULT 10)
RETURNS TABLE (
    video_id INTEGER,
    score DECIMAL(6,4),
    rank INTEGER
) AS $$
BEGIN
    RETURN QUERY
    SELECT
        unnest(r.recommended_video_ids) AS video_id,
        unnest(r.scores) AS score,
        generate_series(1, array_length(r.recommended_video_ids, 1)) AS rank
    FROM output.als_recommendations r
    WHERE r.user_id = p_user_id
      AND r.is_active = true
    ORDER BY r.generated_at DESC
    LIMIT p_limit;
END;
$$ LANGUAGE plpgsql;

-- Function to deactivate old recommendations (keep only latest N per user)
CREATE OR REPLACE FUNCTION cleanup_old_recommendations(keep_count INTEGER DEFAULT 3)
RETURNS INTEGER AS $$
DECLARE
    deleted_count INTEGER;
BEGIN
    WITH ranked AS (
        SELECT id,
               ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY generated_at DESC) as rn
        FROM output.als_recommendations
        WHERE is_active = true
    )
    UPDATE output.als_recommendations
    SET is_active = false
    WHERE id IN (SELECT id FROM ranked WHERE rn > keep_count);

    GET DIAGNOSTICS deleted_count = ROW_COUNT;
    RETURN deleted_count;
END;
$$ LANGUAGE plpgsql;

COMMENT ON TABLE output.als_recommendations IS 'User-specific video recommendations generated by ALS collaborative filtering.';
COMMENT ON COLUMN output.als_recommendations.recommended_video_ids IS 'Ordered array of video IDs (best first)';
COMMENT ON COLUMN output.als_recommendations.scores IS 'Confidence scores for each video (parallel to video_ids)';
COMMENT ON COLUMN output.als_recommendations.model_version IS 'Format: als_vX.Y_YYYYMMDD';
